#!/usr/bin/env bash

set -e

# R-syncs files inside an android phone with existing direcroy.
# It takes one argument, the path to sync. This command is supposed to be run from within the sync directory

# @TODO accept 2nd argument for the destination

dir_src=/run/user/$UID/gvfs/mtp*
dir_dest=$(pwd)

path_to_sync=$1

# Default to "."
path_to_sync=${path_to_sync:-.}

# Remove trailing slash
path_to_sync=${path_to_sync%/}

cmd="rsync -av $dir_src/$path_to_sync/ $path_to_sync -n"

cd $dir_src
[ ! -d "Phone" ] && echo "[ERROR] Phone not mounted. Exiting now." && exit

echo "[CMD] $cmd"
read -p 'Run? y/n ' run

[ $run != "y" ] && echo "Cancled." && exit

$cmd

